#Requires -Version 5.0
<#
PoE Injector Connectivity Test for Antaira LNP-0500G-BT-24
Test: Load each port individually to isolate the fault
#>

Write-Host "============================================"
Write-Host "PoE Injector Fault Diagnosis Tool"
Write-Host "============================================"
Write-Host ""
Write-Host "STEP 1: Visual Inspection Checklist"
Write-Host "---"
Write-Host "1. [ ] Are power cables to V1 and V2 both securely connected?"
Write-Host "2. [ ] Is the input 24V LED on the injector itself lit (green)?"
Write-Host "3. [ ] Are output ports 1-4 showing ANY link LEDs? (usually green when connected)"
Write-Host "4. [ ] Do any of the 4 output ports have RED fault LEDs?"
Write-Host ""
Write-Host "STEP 2: One-by-One Port Test"
Write-Host "---"
Write-Host "Instructions:"
Write-Host "a) DISCONNECT ALL devices from the injector"
Write-Host "b) Observe: Does FAULT LED turn OFF? (yes=port issue, no=power issue)"
Write-Host "c) Connect ONLY the load cell board to Port 1"
Write-Host "d) Wait 10 seconds. Note: Does FAULT light up?"
Write-Host "e) If no fault: GOOD. Connect PC USB-to-Eth to Port 3."
Write-Host "f) If fault: Load cell is the culprit. CHECK ITS WIRING."
Write-Host "g) Then test LaunchPad on Port 2 alone."
Write-Host ""
Write-Host "STEP 3: Cable Verification"
Write-Host "---"
Write-Host "Use a cable tester or try:"
Write-Host "  - Swap cables between ports (if fault moves, cable is bad)"
Write-Host "  - Try a brand new CAT6 cable on each port"
Write-Host "  - Make sure no exposed wires are touching the connectors"
Write-Host ""
Write-Host "STEP 4: Current Draw Check (if you have a multimeter)"
Write-Host "---"
Write-Host "PoE+ max is typically 90W total on good injectors."
Write-Host "  - Load cells usually draw 500mA-1A at 24V = 12-24W (safe)"
Write-Host "  - TI LaunchPad + Ethernet PHY = ~100-200mA @ 5V derived = 5-10W"
Write-Host "  - USB-to-Eth adapter = ~100-500mA = 0.5-2.4W"
Write-Host "If combined is >30W on ONE port, injector will fault."
Write-Host ""
Write-Host "STEP 5: Test Connectivity (assuming no FAULT after Step 2)"
Write-Host "---"
Write-Host "Run these commands on your PC:"
Write-Host ""
Write-Host "# Test PC -> LaunchPad Ethernet"
Write-Host "ping 169.254.x.x   (if LaunchPad set to auto-config)"
Write-Host ""
Write-Host "# Test PC -> Load cell"
Write-Host "# (depends on load cell's Ethernet config)"
Write-Host "ping <load_cell_ip>"
Write-Host ""
Write-Host "# If ARP discovery enabled on devices:"
Write-Host "arp -a"
Write-Host ""
Write-Host "STEP 6: Check Device Configs"
Write-Host "---"
Write-Host "LaunchPad:"
Write-Host "  - Default IP mode? DHCP or static 169.254.x.x?"
Write-Host "  - MAC address visible in device logs?"
Write-Host ""
Write-Host "Load cell:"
Write-Host "  - Does it have an IP config sticker?"
Write-Host "  - Try pinging common defaults: 192.168.1.100, 10.0.0.x"
Write-Host ""
Write-Host "USB-to-Eth:"
Write-Host "  - Windows auto-assigned APIPA IP?"
Write-Host "  - Check Network Connections > Ethernet adapter"
Write-Host ""

Write-Host "============================================"
Write-Host "Ready to start? Answer the checklist above."
Write-Host "============================================"
